---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: prometheus
    run_list:
      - recipe[prometheus::default]
    verifier:
      inspec_tests:
        - test/integration/prometheus
    attributes: {
      "prometheus": {
        "jobs": {
          "test_job": {
            "scrape_interval": "15s"
          }
        }
      }
    }
