---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: prometheus
    run_list:
      - recipe[prometheus::default]
    verifier:
      inspec_tests:
        - test/integration/prometheus
    attributes: {
      "prometheus": {
        "config": {
          "alerting": {
            "alertmanagers": [
              {
                "scheme": "http",
                "static_configs": [
                  {
                    "targets": ["localhost:9093"],
                  }
                ]
              }
            ],
          },
          "scrape_configs": {
            "prometheus": {
              "metrics_path": "/metrics",
              "static_configs": [
                {
                  "targets": ["localhost:9090"],
                }
              ]
            },
            "consul": {
              "scrape_interval": "15s",
              "consul_sd_configs": [
                {
                  "server": "localhost:8500",
                  "services": ["node_exporter"]
                }
              ],
              "relabel_configs": [
                {
                  "source_labels": ["__meta_consul_dc"],
                  "target_label": "dc",
                  "regex": "(.*)",
                  "replacement": "${1}"
                }
              ]
            },
            "test": {
              "scrape_interval": "15s",
              "relabel_configs": [
                {
                  "source_labels": ["__address__"],
                  "target_label": "__param_target",
                  "regex": "(.*)(:80)?",
                  "replacement": "${1}"
                },
                {
                  "source_labels": ["__param_target"],
                  "regex": "(.*)",
                  "target_label": "instance",
                  "replacement": "${1}"
                }
              ]
            }
          }
        }
      }
    }
  - name: alertmanager
    run_list:
      - recipe[prometheus::alertmanager]
    verifier:
      inspec_tests:
        - test/integration/alertmanager
    attributes: {
      "alertmanager": {
        "config": {
          "receivers": [
            {
              "name": "slack",
              "slack_configs": [
                {
                  "api_url": "https://api.slack.com",
                  "channel": "#alerts",
                  "send_resolved": true,
                }
              ]
            }
          ],
          "route": {
            "group_by": [
              "alertname",
              "cluster",
              "service",
            ],
            "group_interval": "5m",
            "group_wait": "30s",
            "receiver": "slack",
            "repeat_interval": "4h"
          }
        }
      }
    }
  - name: pushgateway
    run_list:
      - recipe[prometheus::pushgateway]
    verifier:
      inspec_tests:
        - test/integration/pushgateway
  - name: trickster
    run_list:
      - recipe[prometheus::trickster]
    verifier:
      inspec_tests:
        - test/integration/trickster
  - name: node-exporter
    run_list:
      - recipe[prometheus::node_exporter]
    verifier:
      inspec_tests:
        - test/integration/node_exporter
  - name: blackbox-exporter
    run_list:
      - recipe[prometheus::blackbox_exporter]
    verifier:
      inspec_tests:
        - test/integration/blackbox_exporter